// Generated locale keys - Complete translation keys for KlienCash app
class LocaleKeys {
  // Onboarding Page
  static const String onBoardingPage1Title = 'onBoardingPage1Title';
  static const String onBoardingPage1Subtitle = 'onBoardingPage1Subtitle';
  static const String onBoardingPage2Title = 'onBoardingPage2Title';
  static const String onBoardingPage2Subtitle = 'onBoardingPage2Subtitle';
  static const String onBoardingPage3Title = 'onBoardingPage3Title';
  static const String onBoardingPage3Subtitle = 'onBoardingPage3Subtitle';
  static const String skipButton = 'skipButton';
  static const String getStartedButton = 'getStartedButton';

  // Add User Page
  static const String createUser = 'createUser';
  static const String userBusinessInfo = 'userBusinessInfo';
  static const String username = 'username';
  static const String businessName = 'businessName';
  static const String address = 'address';
  static const String contactsInfo = 'contactsInfo';
  static const String phoneNumber = 'phoneNumber';
  static const String email = 'email';
  static const String done = 'done';
  static const String fillAllFields = 'fillAllFields';

  // Home Page
  static const String clientCash = 'clientCash';
  static const String buildByJ = 'buildByJ';
  static const String hallo = 'hallo';

  // Settings Page
  static const String settings = 'settings';
  static const String userInformation = 'userInformation';
  static const String editUserInfo = 'editUserInfo';
  static const String bankExample = 'bankExample';
  static const String bankNumber = 'bankNumber';
  static const String accountNameExample = 'accountNameExample';
  static const String accountName = 'accountName';
  static const String languageLabel = 'languageLabel';
  static const String indonesian = 'indonesian';
  static const String english = 'english';
  static const String theme = 'theme';
  static const String blue = 'blue';
  static const String pink = 'pink';
  static const String black = 'black';
  static const String error = 'error';
  static const String ok = 'ok';
  static const String understood = 'understood';
  static const String fillFieldsFirst = 'fillFieldsFirst';
  static const String successAddPaymentMethod = 'successAddPaymentMethod';
  static const String successEditPaymentMethod = 'successEditPaymentMethod';
  static const String successDeletePaymentMethod = 'successDeletePaymentMethod';
  static const String successUpdateUserInfo = 'successUpdateUserInfo';
  static const String errorOccurred = 'errorOccurred';
  static const String pleaseCheckInput = 'pleaseCheckInput';
  static const String selectDateLabel = 'selectDateLabel';
  static const String warning = 'warning';

  // Invoice Pages
  static const String invoiceList = 'invoiceList';
  static const String addNewInvoice = 'addNewInvoice';
  static const String invoiceDetails = 'invoiceDetails';
  static const String invoicePdfPreview = 'invoicePdfPreview';
  static const String invoice = 'invoice';
  static const String billTo = 'billTo';
  static const String issued = 'issued';
  static const String dueDate = 'dueDate';
  static const String itemTransactions = 'itemTransactions';
  static const String agenda = 'agenda';
  static const String total = 'total';
  static const String status = 'status';
  static const String operationalCost = 'operationalCost';
  static const String subtotal = 'subtotal';
  static const String tax = 'tax';
  static const String discount = 'discount';
  static const String rounding = 'rounding';
  static const String paymentInfo = 'paymentInfo';
  static const String paymentMethod = 'paymentMethod';
  static const String selectPaymentMethod = 'selectPaymentMethod';
  static const String invoiceAutoGenerated = 'invoiceAutoGenerated';
  static const String noInvoice = 'noInvoice';
  static const String addInvoiceFirst = 'addInvoiceFirst';
  static const String invoiceTitle = 'invoiceTitle';
  static const String notes = 'notes';
  static const String printInvoices = 'printInvoices';
  static const String invoiceInformation = 'invoiceInformation';
  static const String clientInformation = 'clientInformation';
  static const String financialDetails = 'financialDetails';
  static const String projectTitle = 'projectTitle';
  static const String invoiceNumber = 'invoiceNumber';
  static const String clientName = 'clientName';
  static const String project = 'project';
  static const String dpPartial = 'dpPartial';
  static const String fullyPaid = 'fullyPaid';
  static const String successAddInvoice = 'successAddInvoice';

  // Client Pages
  static const String addClient = 'addClient';
  static const String allClients = 'allClients';
  static const String clientName2 = 'clientName2';
  static const String clientAddress = 'clientAddress';
  static const String editClient = 'editClient';
  static const String deleteClient = 'deleteClient';
  static const String cancel = 'cancel';
  static const String yesDelete = 'yesDelete';
  static const String noClient = 'noClient';
  static const String addClientFirst = 'addClientFirst';
  static const String successAddClient = 'successAddClient';
  static const String successDeleteClient = 'successDeleteClient';
  static const String successEditClient = 'successEditClient';

  // Project Pages
  static const String allProjects = 'allProjects';
  static const String addProjects = 'addProjects';
  static const String noProject = 'noProject';
  static const String addProjectFirst = 'addProjectFirst';
  static const String editProject = 'editProject';
  static const String deleteProject = 'deleteProject';
  static const String projectRanking = 'projectRanking';
  static const String projectStatus = 'projectStatus';
  static const String clientInProjects = 'clientInProjects';
  static const String agendaDescription = 'agendaDescription';
  static const String priceInfo = 'priceInfo';
  static const String agendaLabel = 'agendaLabel';
  static const String description = 'description';
  static const String initialPrice = 'initialPrice';
  static const String startEndDate = 'startEndDate';
  static const String selectDate = 'selectDate';
  static const String until = 'until';
  static const String created = 'created';
  static const String holdToEdit = 'holdToEdit';
  static const String successAddProject = 'successAddProject';
  static const String successDeleteProject = 'successDeleteProject';
  static const String successEditProject = 'successEditProject';
  static const String pleasSelectDates = 'pleasSelectDates';
  static const String pleasFillRequired = 'pleasFillRequired';

  // Payment Pages
  static const String paymentPage = 'paymentPage';
  static const String addPayment = 'addPayment';
  static const String amount = 'amount';
  static const String uploadPaymentProof = 'uploadPaymentProof';
  static const String selectProject = 'selectProject';
  static const String noPayment = 'noPayment';
  static const String addPaymentFirst = 'addPaymentFirst';

  // Operasional Pages
  static const String operasionalPage = 'operasionalPage';
  static const String noProjects = 'noProjects';
  static const String addOperasionalFirst = 'addOperasionalFirst';
  static const String title = 'title';
  static const String quantity = 'quantity';
  static const String deleteItem = 'deleteItem';
  static const String yesConfirm = 'yesConfirm';
  static const String edit = 'edit';
  static const String fillFieldsFirst2 = 'fillFieldsFirst2';
  static const String successAddModal = 'successAddModal';
  static const String successEditModal = 'successEditModal';
  static const String successDeleteModal = 'successDeleteModal';

  // Report Pages
  static const String reportPage = 'reportPage';
  static const String overview = 'overview';
  static const String newClientsMonthly = 'newClientsMonthly';
  static const String summaryOverall = 'summaryOverall';
  static const String totalInvoice = 'totalInvoice';
  static const String totalPaid = 'totalPaid';
  static const String mostInvoiceStatus = 'mostInvoiceStatus';
  static const String noChartData = 'noChartData';
  static const String noInvoiceData = 'noInvoiceData';
  static const String noProjectsData = 'noProjectsData';
  static const String loading = 'loading';

  // Navigation/Menu
  static const String client = 'client';
  static const String projects = 'projects';
  static const String operasional = 'operasional';
  static const String payment = 'payment';
  static const String report = 'report';

  // Select/Dropdown
  static const String selectClient = 'selectClient';
  static const String selectProjects = 'selectProjects';
  static const String selectStatus = 'selectStatus';
  static const String noOperationalCost = 'noOperationalCost';

  // Payment Methods
  static const String cash = 'cash';
  static const String bank = 'bank';
  static const String eWallet = 'eWallet';

  // Common Messages
  static const String fillAllFieldsRequired = 'fillAllFieldsRequired';
  static const String successAdded = 'successAdded';
  static const String successDeleted = 'successDeleted';
  static const String successEdited = 'successEdited';
  static const String operationalTotal = 'operationalTotal';
  static const String pay = 'pay';

  // startdate and endDate
  static const String startDateAndEndDate = 'startDateAndEndDate';
  static const String save = 'save';
  static const String deleteClientConfirm = 'deleteClientConfirm';
  static const String start = 'start';
  static const String nothingChanges = 'nothingChanges';
  static const String opeartional = 'operational';
  static const String adding = 'adding';
  static const String projectPrice = 'projectsPrice';
  static const String free = 'free';
  static const String addNewPaymentMethod = 'addNewPaymentMethod';
  static const String or = 'or';
  static const String onBehalfOf = 'onBehalfOf';
  static const String clickToAdd = 'clickToAdd';
  static const String select = 'select';
  static const String emptyFilter = 'emptyFilter';
  static const String search = 'search';
  static const String installments = 'installments';
  static const String dp = 'DP';
}
